version: "3.8"
services:
  mysql:
    image: mysql:lts
    container_name: mysql_NestJS_GraphQL_Example
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjsGraphQLExample
      MYSQL_USER: user_angel
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
